SUPABASE_URL = "https://tervudnniyobpeancuhj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlcnZ1ZG5uaXlvYnBlYW5jdWhqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NDA0MTgyNCwiZXhwIjoyMDc5NjE3ODI0fQ.xPUQ6yq0OpkmLzzApMRc-uKyYyKwDqHOd5RcATO_xBY"
